baseURL = "https://www.openkermit.org/"
paginate = 4
theme = "fluency"
title = "Open Kermit Project"
refLinksErrorLevel = "WARNING"

disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true
languageCode = "en-US"

[language]
locale = "en-US"

[author]
name = "John Goerzen"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = "always"

[[menu.main]]
  identifier = "downloads"
  name = "Get Kermit"
  url = "/downloads/"
  weight = 1
[[menu.main]]
  identifier = "doc"
  name = "Documentation"
  url = "/doc/"
  weight = 2
[[menu.main]]
  identifier = "support"
  name = "Support"
  url = "/support/"
  weight = 3
[[menu.main]]
  identifier = "about"
  name = "About This Site"
  url = "/about-this-site/"
  weight = 4

[[menu.footer]]
  identifier = "copyright"
  url = "/about-this-site/"
  name = "Copyright and License"
  weight = 1

[[menu.footer]]
  identifier = "github"
  url = "https://github.com/openkermit"
  name = "Github"
  weight = 2

[params]
  custom_css = []
  description = "Home of continuing development of C-Kermit"
  enable_mathjax = false
  keywords = ["hugo", "latex", "theme"]
  disableComment = true
  disableAnchorHeading = true
  mainSections = ["posts", "pics"]
  copyright = "(c) 2026 John Goerzen"

[taxonomies]
  series = "series"
  tag = "tags"
  category = "categories"
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

